### ISSUE TITLE
[BUG] Discover interval small than 1000ms , will have some trouble

### ISSUE THREAD

**Issue by WPH95** [dashbase/es-query-proxy#107]
![image](https://user-images.githubusercontent.com/2732352/35901014-b028b24c-0c0f-11e8-9fab-d2e1e3910c71.png)

**Comment by WPH95** [comment]
@javasoze  dashbase cloud support  ms interval ?

**Comment by javasoze** [comment]
no, smallest granularity is seconds.

**Comment by javasoze** [comment]
time granularity < 1s is not currently supported. Will close for now.
