### ISSUE TITLE
Prefix query does not always work

### ISSUE THREAD

**Issue by javasoze** [dashbase/es-query-proxy#31]
<img width="1387" alt="screen shot 2018-01-09 at 8 31 05 am" src="https://user-images.githubusercontent.com/168714/34731578-8e7f6c4e-f517-11e7-9b99-5a0cd970e14d.png">
<img width="1388" alt="screen shot 2018-01-09 at 8 30 53 am" src="https://user-images.githubusercontent.com/168714/34731579-8ea8e6a0-f517-11e7-96f0-e55f293770bb.png">

**Comment by SinceJune** [comment]
actually, i found the data on staging is not stable either.
![image](https://user-images.githubusercontent.com/19381524/34765536-bf00f566-f62c-11e7-86f4-ed3c3ac8dae8.png)

![image](https://user-images.githubusercontent.com/19381524/34765521-b00a895a-f62c-11e7-83ae-1ba15bbbec40.png)

**Comment by SinceJune** [comment]
MAY it is not a bug of es-query-proxy?
