### ISSUE TITLE
Use a java object here instead of constructing a map

### ISSUE THREAD

**Issue by javasoze** [dashbase/es-query-proxy#49]
In this part of the code:
https://github.com/dashbase/es-query-proxy/blob/master/src/main/java/io/dashbase/EsQueryProxyResource.java#L190

Consider using a java object, e.g. 
```
public class EsFieldsInfo {
    public boolean searchable;
    public boolean aggregatable;
}

public class EsFieldResponse {
    public Map<String, Map<String, EsFieldsInfo>> fields = new HashMap<>();
}
```
Instead of constructing a Map by hand. To make the code more maintainable.

**Comment by WPH95** [comment]
#89
