### ISSUE TITLE
Dev Tool does not work

### ISSUE THREAD

**Issue by javasoze** [dashbase/es-query-proxy#66]
See screenshot:

<img width="1418" alt="screen shot 2018-01-24 at 11 09 39 am" src="https://user-images.githubusercontent.com/168714/35351894-2ea1e34c-00f7-11e8-9d59-4ed327263e1c.png">

Could be some simple setting issue, but I think it is important to get this working.

**Comment by lfkdsk** [comment]
@javasoze @WPH95 bug-fix-pr:https://github.com/dashbase/es-query-proxy/pull/67
