### ISSUE TITLE
timelion on staging stopped working and is now stuck in that state

### ISSUE THREAD

**Issue by javasoze** [dashbase/es-query-proxy#71]
See screenshot
<img width="1421" alt="screen shot 2018-01-26 at 4 26 42 pm" src="https://user-images.githubusercontent.com/168714/35466102-d2ee450c-02b5-11e8-8ad4-9dc73ba9e4d7.png">

**Comment by WPH95** [comment]
![image](https://user-images.githubusercontent.com/2732352/35468373-392f490a-0357-11e8-9e51-e1a2b5035b3c.png)

**Comment by WPH95** [comment]
https://staging.dashbase.io:5601/app/timelion#?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-15m,interval:auto,mode:quick,timezone:Asia%2FShanghai,to:now))&_a=(columns:2,interval:auto,rows:2,selected:0,sheet:!('.es(*,%20index%3D%22nginx_json%22,%20metric%3Davg:bytesSent),%0A.es(*,%20index%3D%22nginx_json%22,%20metric%3Dmax:bytesSent)'))

**Comment by WPH95** [comment]
maybe staging api unstabitily

**Comment by WPH95** [comment]
i will improve Exception for human soon

**Comment by javasoze** [comment]
I think the problem is if the time range is out of index scope, e.g. using a static time range over a day ago, then you will see this error message instead of just show 0. I think it is an issue with handling the empty result set on the es proxy side.

**Comment by WPH95** [comment]
yep, aggregations depend on  RapidResponse.request.timeRangeFilter
 if timeRangeFilter is null , and  es min_doc_count == 0 , will have some trouble。
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_minimum_document_count_4
