### ISSUE TITLE
[BUG]discover not show hits

### ISSUE THREAD

**Issue by WPH95** [dashbase/es-query-proxy#80]
![image](https://user-images.githubusercontent.com/2732352/35550152-25cecf9c-05c4-11e8-9b86-045c62ca772b.png)

_id have duplicate

**Comment by SinceJune** [comment]
https://github.com/dashbase/es-query-proxy/blob/master/src/main/java/io/dashbase/es/queries/QueryConverter.java#L265
从代码上来看应该是dashbase那边的问题, 目前是直接把dashbase.docId当成是_id来处理,
不过目前我没办法复现了.

**Comment by WPH95** [comment]
cc @javasoze

**Comment by SinceJune** [comment]
fixed in #109
